Bigamer/Bigamer.Presentation/Controllers/AuthController.cs
using Bigamer.Application.Requests.User.Commands.UserLogin;
using Bigamer.Application.Requests.User.Commands.UserRegister;
using Bigamer.Application.Features.User.Commands.UserLoginCommand;
using Bigamer.Application.Features.User.Commands.UserLogoutCommand;
using Bigamer.Application.Features.User.Commands.UserRegisterCommand;
using MediatR;
using Microsoft.AspNetCore.Mvc;

namespace Bigamer.Presentation.Controllers;

[Route("[controller]/[action]")]
public class AuthController : Controller
{
    private readonly IMediator _mediator;

    public AuthController(IMediator mediator)
    {
        _mediator = mediator;
    }

    [HttpGet]
    public IActionResult Login()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Login([FromBody] UserLoginRequest request)
    {
        var command = new UserLoginCommand(request);
        await _mediator.Send(command);

        return RedirectToAction("Index", "Home");
    }

    [HttpGet]
    public IActionResult Register()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Register([FromBody] UserRegisterRequest request)
    {
        var command = new UserRegisterCommand(request);
        await _mediator.Send(command);

        return Ok();
    }

    [HttpPost]
    public async Task<IActionResult> Logout()
    {
        var command = new UserLogoutCommand();
        await _mediator.Send(command);

        return RedirectToAction("Login");
    }
}

Bigamer/Bigamer.Presentation/Controllers/TeamController.cs
using Bigamer.Application.Requests.Team.Commands;
using Bigamer.Application.Requests.Team.Commands.TeamAddPlayerRequest;
using Bigamer.Application.Requests.Team.Commands.TeamAddRequest;
using Bigamer.Application.Requests.Team.Queries.TeamGetRequest;
using Bigamer.Application.Features.Team.Commands.TeamAddCommand;
using Bigamer.Application.Features.Team.Commands.TeamAddLinkCommand;
using Bigamer.Application.Features.Team.Commands.TeamAddPlayerCommand;
using Bigamer.Application.Features.Team.Queries.TeamGetQuery;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Bigamer.Presentation.Controllers;

// [Authorize]
public class TeamController : Controller
{
    private readonly IMediator _mediator;

    public TeamController(IMediator mediator)
    {
        _mediator = mediator;
    }

    [HttpGet]
    [Route("[controller]/[action]/{teamId:guid}")]
    public async Task<IActionResult> Index(Guid teamId)
    {
        var query = new TeamGetQuery(new TeamGetRequest
        {
            TeamId = teamId
        });
        var response = await _mediator.Send(query);
        
        return View(response);
    }

    [Authorize(Roles = "admin")]
    [HttpPost]
    [Route("api/[controller]/[action]")]
    public async Task<IActionResult> AddAsync([FromBody] TeamAddRequest request)
    {
        var command = new TeamAddCommand(request);
        await _mediator.Send(command);

        return Ok();
    }
    
    [Authorize(Roles = "admin")]
    [HttpPost]
    [Route("api/[controller]/[action]")]
    public async Task<IActionResult> AddPlayerAsync([FromBody] TeamAddPlayerRequest request)
    {
        var command = new TeamAddPlayerCommand(request);
        await _mediator.Send(command);
 
        return Ok();
    }
    
    // [Authorize(Roles = "admin")]
    [HttpPost]
    [Route("api/[controller]/[action]")]
    public async Task<IActionResult> AddLinkAsync([FromBody] TeamAddLinkRequest request)
    {
        var command = new TeamAddLinkCommand(request);
        await _mediator.Send(command);
 
        return Ok();
    }
}

Bigamer/Bigamer.Presentation/Controllers/TeamListController.cs
using Bigamer.Application.Features.Team.Queries.TeamGetAllQuery;
using Bigamer.Application.Requests.Team.Queries.TeamGetAllRequest;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Bigamer.Presentation.Controllers;

[Authorize]
[Route("[controller]/[action]")]
public class TeamListController : Controller
{
    private readonly IMediator _mediator;

    public TeamListController(IMediator mediator)
    {
        _mediator = mediator;
    }

    [HttpGet]
    public async Task<IActionResult> Index([FromQuery] int offset = 0, [FromQuery] int limit = 6)
    {
        var query = new TeamGetAllQuery(new TeamGetAllRequest
        {
            Offset = offset,
            Limit = limit
        });
        var result = await _mediator.Send(query);
        
        return View(result);
    }
}

Bigamer/Bigamer.Presentation/Views/TeamList/Index.cshtml
@using Bigamer.Shared.Enums
@model Bigamer.Application.Requests.Team.Queries.TeamGetAllRequest.TeamGetAllResponse

@{
    Layout = Layout;
}

<!-- ===========Banner Section start Here========== -->
<section class="pageheader-section" style="background-image: url(../assets/images/pageheader/bg.jpg);">
    <div class="container">
        <div class="section-wrapper text-center text-uppercase">
            <h2 class="pageheader-title">our team</h2>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb justify-content-center mb-0">
                    <li class="breadcrumb-item">
                        <a asp-controller="Home">Home</a>
                    </li>
                    <li class="breadcrumb-item active" aria-current="page">Team</li>
                </ol>
            </nav>
        </div>
    </div>
</section>
<!-- ===========Banner Section Ends Here========== -->


<!-- ===========Player  Section start Here========== -->
<div class="player-section padding-top padding-bottom">
    <div class="container">
        <div class="section-wrapper">
            <div style="display: flex; margin-left: auto; margin-right: auto; justify-content: center; margin-bottom: 10px;">
                @if (Model.CurrentOffset != 0)
                {
                    <a
                        asp-action="Index"
                        asp-route-offset="@(Math.Max(Model.CurrentOffset - Model.CurrentLimit, 0))"
                        asp-route-limit="@Model.CurrentLimit"
                        style="margin-right: 25px; width: fit-content">
                        Previous..
                    </a>
                }
                @if (Model.CurrentOffset + Model.CurrentLimit < Model.TotalCount)
                {
                    <a
                        asp-action="Index"
                        asp-route-offset="@(Model.CurrentOffset + Model.CurrentLimit)"
                        asp-route-limit="@Model.CurrentLimit">
                        Next..
                    </a>
                }
            </div>
            <div class="row g-4 justify-content-center">
                @foreach (var team in Model.Teams)
                {
                    <div class="col-lg-4 col-sm-6 col-12">
                        <div class="player-item-2 text-center" style="background-image: url(../assets/images/team/2.jpg);">
                            <div class="player-inner-2">
                                <div class="player-thumb-2">
                                    <a asp-action="Index" asp-route-teamId="@team.TeamId" asp-controller="Team">
                                        <img
                                            style="height: 220px;"
                                            src="@team.ImageUrl" alt="team-img">
                                    </a>
                                </div>
                                <div class="player-content-2">
                                    <a asp-action="Index" asp-route-teamId="@team.TeamId" asp-controller="Team">
                                        <h2>@team.Name</h2>
                                    </a>
                                    <ul class="match-social-list d-flex flex-wrap align-items-center justify-content-center">
                                        @foreach (var link in team.Links)
                                        {
                                            string linkImage;
                                            switch (link.ServiceName)
                                            {
                                                case LinkType.Undefined:
                                                case LinkType.Hltv:
                                                    linkImage = "https://play-lh.googleusercontent.com/chI-8vX4CIbO-pm14tb5UAjip20CwmytQPdz8sBmqNjPqTp1tptpBOZc-aGyYqDesw";
                                                    break;
                                                case LinkType.Yt:
                                                    linkImage = "../assets/images/match/social-2.png";
                                                    break;
                                                case LinkType.Twitch:
                                                    linkImage = "../assets/images/match/social-3.png";
                                                    break;
                                                default:
                                                    throw new ArgumentOutOfRangeException();
                                            }

                                            <li>
                                                <a href="@link.Link">
                                                    <img style="height: 50px; border-radius: 100px" src=@linkImage alt="@link.ServiceName">
                                                </a>
                                            </li>
                                        }
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>
<!-- ===========Player  Section Ends Here========== -->


<!-- ===========CTA Section start Here========== -->
<section class="cta-section padding-bottom">
    <div class="container">
        <div class="cta-wrapper item-layer">
            <div class="cta-item px-4 px-sm-5 pt-4 pt-sm-5 pt-lg-0" style="background-image: url(../assets/images/cta/bg.jpg);">
                <div class="row align-items-center">
                    <div class="col-lg-6">
                        <div class="cta-content">
                            <p class="theme-color text-uppercase ls-2">Let's Play together</p>
                            <h2 class="mb-3">
                                JOIN <span class="theme-color text-uppercase">bigamer</span> ESPORTS TO BECOME
                                NEXT PRO GAMER TODAY!
                            </h2>
                            <p class="mb-4">
                                Distinctively provide acces mutfuncto users whereas transparent
                                proceses somes ncentivize eficient functionalities rather than an
                                extensible archtectur services and cross
                            </p>
                            <a asp-action="Register" asp-controller="Auth" class="default-button">
                                <span>Join Community <i class="icofont-circled-right"></i></span>
                            </a>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="cta-thumb text-end">
                            <img src="~/assets/images/cta/01.png" alt="gamer-img">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- ===========CTA Section Ends Here========== -->