Bigamer/Bigamer.Presentation/Controllers/AdminProfileController.cs
using Bigamer.Application.Features.User.Queries.UserGetInfoQuery;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Bigamer.Presentation.Controllers;

[Authorize(Roles = "admin")]
[Route("Admin/Profile")]
public class AdminProfileController : Controller
{
    private readonly IMediator _mediator;

    public AdminProfileController(IMediator mediator)
    {
        _mediator = mediator;
    }

    public async Task<IActionResult> Index()
    {
        var query = new UserGetInfoQuery();
        var userInfo = await _mediator.Send(query);
        
        return View(userInfo);
    }
}

Bigamer/Bigamer.Presentation/Controllers/AuthController.cs
using Bigamer.Application.Requests.User.Commands.UserLogin;
using Bigamer.Application.Requests.User.Commands.UserRegister;
using Bigamer.Application.Features.User.Commands.UserLoginCommand;
using Bigamer.Application.Features.User.Commands.UserLogoutCommand;
using Bigamer.Application.Features.User.Commands.UserRegisterCommand;
using MediatR;
using Microsoft.AspNetCore.Mvc;

namespace Bigamer.Presentation.Controllers;

[Route("[controller]/[action]")]
public class AuthController : Controller
{
    private readonly IMediator _mediator;

    public AuthController(IMediator mediator)
    {
        _mediator = mediator;
    }

    [HttpGet]
    public IActionResult Login()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Login([FromBody] UserLoginRequest request)
    {
        var command = new UserLoginCommand(request);
        await _mediator.Send(command);

        return RedirectToAction("Index", "Home");
    }

    [HttpGet]
    public IActionResult Register()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Register([FromBody] UserRegisterRequest request)
    {
        var command = new UserRegisterCommand(request);
        await _mediator.Send(command);

        return Ok();
    }

    [HttpPost]
    public async Task<IActionResult> Logout()
    {
        var command = new UserLogoutCommand();
        await _mediator.Send(command);

        return RedirectToAction("Login");
    }
}

Bigamer/Bigamer.Presentation/Controllers/MatchListController.cs
using Bigamer.Application.Features.Match.Queries.MatchGetAllQuery;
using Bigamer.Application.Requests.Match.Queries.MatchGetAllRequest;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Bigamer.Presentation.Controllers;

[Authorize]
[Route("[controller]/[action]")]
public class MatchListController : Controller
{
    private readonly IMediator _mediator;

    public MatchListController(IMediator mediator)
    {
        _mediator = mediator;
    }

    [HttpGet]
    public async Task<IActionResult> Index(
        [FromQuery] string? filter, 
        [FromQuery] int offset = 0,
        [FromQuery] int limit = 5)
    {
        var getAllMatchesQuery = new MatchGetAllQuery(new MatchGetAllRequest
        {
            Filter = filter,
            Offset = offset,
            Limit = limit
        });
        var allMatches = await _mediator.Send(getAllMatchesQuery);
        
        return View(allMatches);
    }
}

Bigamer/Bigamer.Presentation/Controllers/TeamListController.cs
using Bigamer.Application.Features.Team.Queries.TeamGetAllQuery;
using Bigamer.Application.Requests.Team.Queries.TeamGetAllRequest;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Bigamer.Presentation.Controllers;

[Authorize]
[Route("[controller]/[action]")]
public class TeamListController : Controller
{
    private readonly IMediator _mediator;

    public TeamListController(IMediator mediator)
    {
        _mediator = mediator;
    }

    [HttpGet]
    public async Task<IActionResult> Index([FromQuery] int offset = 0, [FromQuery] int limit = 6)
    {
        var query = new TeamGetAllQuery(new TeamGetAllRequest
        {
            Offset = offset,
            Limit = limit
        });
        var result = await _mediator.Send(query);
        
        return View(result);
    }
}

Bigamer/Bigamer.Presentation/Views/Shared/_AdminLayout.cshtml
@using Microsoft.AspNetCore.Identity
@using Bigamer.Domain.Entities
@using System.Security.Claims
@inject SignInManager<User> SignInManager

@{
    var userEmailClaim = SignInManager.Context.User.Claims
        .FirstOrDefault(i => i.Type.Equals(ClaimTypes.Email));

    var adminEmailToShow = userEmailClaim is null
        ? "Admin"
        : userEmailClaim.Value;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="keywords"
          content="wrappixel, admin dashboard, html css dashboard, web dashboard, bootstrap 5 admin, bootstrap 5, css3 dashboard, bootstrap 5 dashboard, Ample lite admin bootstrap 5 dashboard, frontend, responsive bootstrap 5 admin template, Ample admin lite dashboard bootstrap 5 dashboard template">
    <meta name="description"
          content="Ample Admin Lite is powerful and clean admin dashboard template, inpired from Bootstrap Framework">
    <meta name="robots" content="noindex,nofollow">
    <title>Ample Admin Lite Template by WrapPixel</title>
    <link rel="canonical" href="https://www.wrappixel.com/templates/ample-admin-lite/"/>
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="~/adminAssets/plugins/images/favicon.png">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <!-- Custom CSS -->
    <link href="~/adminAssets/plugins/bower_components/chartist/dist/chartist.min.css" rel="stylesheet">
    <link rel="stylesheet" href="~/adminAssets/plugins/bower_components/chartist-plugin-tooltips/dist/chartist-plugin-tooltip.css">
    <!-- Custom CSS -->
    <link href="~/adminAssets/css/style.min.css" rel="stylesheet">
</head>
<body>
<div id="main-wrapper" data-layout="vertical" data-navbarbg="skin5" data-sidebartype="full"
     data-sidebar-position="absolute" data-header-position="absolute" data-boxed-layout="full">
    <header class="topbar" data-navbarbg="skin5">
        <nav class="navbar top-navbar navbar-expand-md navbar-dark">
            <div class="navbar-header" data-logobg="skin6">
                <!-- ============================================================== -->
                <!-- Logo -->
                <!-- ============================================================== -->
                <a class="navbar-brand" asp-controller="AdminDashboard" asp-action="Index">
                    <!-- Logo icon -->
                    <b class="logo-icon">
                        <!-- Dark Logo icon -->
                        <img src="~/adminAssets/plugins/images/logo-icon.png" alt="homepage"/>
                    </b>
                    <!--End Logo icon -->
                    <!-- Logo text -->
                    <span class="logo-text">
                        <!-- dark Logo text -->
                        <img src="~/adminAssets/plugins/images/logo-text.png" alt="homepage"/>
                    </span>
                </a>
                <!-- ============================================================== -->
                <!-- End Logo -->
                <!-- ============================================================== -->
                <!-- ============================================================== -->
                <!-- toggle and nav items -->
                <!-- ============================================================== -->
                <a class="nav-toggler waves-effect waves-light text-dark d-block d-md-none"
                   href="javascript:void(0)">
                    <i class="ti-menu ti-close"></i>
                </a>
            </div>
            <!-- ============================================================== -->
            <!-- End Logo -->
            <!-- ============================================================== -->
            <div class="navbar-collapse collapse" id="navbarSupportedContent" data-navbarbg="skin5">

                <!-- ============================================================== -->
                <!-- Right side toggle and nav items -->
                <!-- ============================================================== -->
                <ul class="navbar-nav ms-auto d-flex align-items-center">
                    <!-- ============================================================== -->
                    <!-- User profile and search -->
                    <!-- ============================================================== -->
                    <li>
                        <a class="profile-pic" asp-controller="AdminProfile" asp-action="Index">
                            <img src="~/adminAssets/plugins/images/users/varun.jpg" alt="user-img" width="36"
                                 class="img-circle"><span class="text-white font-medium">@adminEmailToShow</span>
                        </a>
                    </li>
                    <!-- ============================================================== -->
                    <!-- User profile and search -->
                    <!-- ============================================================== -->
                </ul>
            </div>
        </nav>
    </header>
    <aside class="left-sidebar" data-sidebarbg="skin6">
        <!-- Sidebar scroll-->
        <div class="scroll-sidebar">
            <!-- Sidebar navigation-->
            <nav class="sidebar-nav">
                <ul id="sidebarnav">
                    <!-- User Profile-->
                    <li class="sidebar-item pt-2">
                        <a class="sidebar-link waves-effect waves-dark sidebar-link"
                           asp-controller="AdminDashboard" asp-action="Index"
                           aria-expanded="false">
                            <i class="far fa-clock" aria-hidden="true"></i>
                            <span class="hide-menu">Dashboard</span>
                        </a>
                    </li>
                    <li class="sidebar-item">
                        <a class="sidebar-link waves-effect waves-dark sidebar-link"
                           asp-controller="AdminProfile" asp-action="Index"
                           aria-expanded="false">
                            <i class="fa fa-user" aria-hidden="true"></i>
                            <span class="hide-menu">Profile</span>
                        </a>
                    </li>
                    <li class="sidebar-item">
                        <a class="sidebar-link waves-effect waves-dark sidebar-link"
                           asp-controller="AdminMatchList" asp-action="Index"
                           aria-expanded="false">
                            <i class="fa fa-table" aria-hidden="true"></i>
                            <span class="hide-menu">Matches</span>
                        </a>
                    </li>
                    <li class="sidebar-item">
                        <a class="sidebar-link waves-effect waves-dark sidebar-link"
                           asp-controller="AdminTeamList" asp-action="Index"
                           aria-expanded="false">
                            <i class="fa fa-table" aria-hidden="true"></i>
                            <span class="hide-menu">Teams</span>
                        </a>
                    </li>
                    <li class="sidebar-item">
                        <a class="sidebar-link waves-effect waves-dark sidebar-link"
                           asp-controller="AdminUserList" asp-action="Index"
                           aria-expanded="false">
                            <i class="fa fa-table" aria-hidden="true"></i>
                            <span class="hide-menu">Users</span>
                        </a>
                    </li>
                    <li class="sidebar-item">
                        <a class="sidebar-link waves-effect waves-dark sidebar-link"
                           asp-controller="Home" asp-action="Index"
                           aria-expanded="false">
                            <i class="fa fa-globe" aria-hidden="true"></i>
                            <span class="hide-menu">Bigamer</span>
                        </a>
                    </li>
                </ul>

            </nav>
            <!-- End Sidebar navigation -->
        </div>
        <!-- End Sidebar scroll-->
    </aside>
    <div class="page-wrapper">
        @RenderBody()

        <footer class="footer text-center">
            2021 © Ample Admin brought to you by
            <a
                href="https://www.wrappixel.com/">
                wrappixel.com
            </a>
        </footer>
    </div>
</div>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
<script src="~/adminAssets/plugins/bower_components/jquery/dist/jquery.min.js"></script>
<!-- Bootstrap tether Core JavaScript -->
<script src="~/adminAssets/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/adminAssets/js/app-style-switcher.js"></script>
<script src="~/adminAssets/plugins/bower_components/jquery-sparkline/jquery.sparkline.min.js"></script>
<!--Wave Effects -->
<script src="~/adminAssets/js/waves.js"></script>
<!--Menu sidebar -->
<script src="~/adminAssets/js/sidebarmenu.js"></script>
<!--Custom JavaScript -->
<script src="~/adminAssets/js/custom.js"></script>
<!--This page JavaScript -->
<!--chartis chart-->
<script src="~/adminAssets/plugins/bower_components/chartist/dist/chartist.min.js"></script>
<script src="~/adminAssets/plugins/bower_components/chartist-plugin-tooltips/dist/chartist-plugin-tooltip.min.js"></script>
<script src="~/adminAssets/js/pages/dashboards/dashboard1.js"></script>
</body>
</html>

Bigamer/Bigamer.Presentation/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using Bigamer.Domain.Entities
@using System.Security.Claims
@inject SignInManager<User> SignInManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Bigamer.Presentation</title>
    <link rel="icon" type="image/png" href="~/assets/images/favicon.png">
    <link rel="stylesheet" href="~/assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/assets/css/animate.css">
    <link rel="stylesheet" href="~/assets/css/icofont.min.css">
    <link rel="stylesheet" href="~/assets/css/swiper.min.css">
    <link rel="stylesheet" href="~/assets/css/lightcase.css">
    <link rel="stylesheet" href="~/assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/assets/css/style.min.css">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/assets/css/animate.css">
    <link rel="stylesheet" href="~/assets/css/icofont.min.css">
    <link rel="stylesheet" href="~/assets/css/swiper.min.css">
    <link rel="stylesheet" href="~/assets/css/lightcase.css">
    <link rel="stylesheet" href="~/assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/assets/css/style.min.css">
    <link rel="stylesheet" href="~/css/main.css">
</head>
<body>
<header class="header-section">
    <div class="container">
        <div class="header-holder d-flex flex-wrap justify-content-between align-items-center">
            <div class="brand-logo d-none d-lg-inline-block">
                <div class="logo">
                    <a asp-action="Index" asp-controller="Home">
                        <img src="~/assets/images/logo/logo.png" alt="logo">
                    </a>
                </div>
            </div>
            <div class="header-menu-part">
                <div class="header-top">
                    <div class="header-top-area">
                        <ul class="left">
                            <li>
                                <span>The best gaming platform</span>
                            </li>
                            <li>
                                Follow us to know about matches!
                            </li>
                        </ul>
                        <ul class="social-icons d-flex align-items-center">
                            <li>
                                <a href="#" class="rss">
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="header-bottom">
                    <div class="header-wrapper">
                        <div class="mobile-logo d-lg-none">
                            <a asp-action="Index" asp-controller="Home">
                                <img src="~/assets/images/logo/logo.png" alt="logo">
                            </a>
                        </div>
                        <div class="menu-area w-100 d-flex justify-content-sm-between">
                            <ul class="menu d-flex justify-content-sm-between w-60">
                                <li>
                                    <a asp-action="Index" asp-controller="Home" class="active">Home</a>
                                </li>
                                @if (SignInManager.IsSignedIn(User))
                                {
                                    <li>
                                        <a asp-action="Index" asp-controller="MatchList" class="active">games</a>
                                    </li>
                                    <li>
                                        <a asp-action="Index" asp-controller="TeamList" class="active">teams</a>
                                    </li>
                                    
                                    if (SignInManager.Context.User.IsInRole("admin"))
                                    {
                                        <li>
                                            <a asp-action="Index" asp-controller="AdminDashboard" class="active">
                                                admin panel
                                            </a>
                                        </li>   
                                    }
                                }
                            </ul>
                            <div style="display: flex; justify-content:center;">
                                @if (!SignInManager.IsSignedIn(User))
                                {
                                    <a asp-action="Login" asp-controller="Auth" class="login">
                                        <i class="icofont-user"></i> <span>LOG IN</span>
                                    </a>
                                    <a asp-action="Register" asp-controller="Auth" class="signup">
                                        <i class="icofont-users"></i> <span>SIGN UP</span>
                                    </a>
                                }
                                else
                                {
                                    <form asp-action="Logout" asp-controller="Auth">
                                        <button class="login">
                                            <i class="icofont-users"></i> <span>LOG OUT</span>
                                        </button>
                                    </form>
                                }
                            </div>

                            <!-- toggle icons -->
                            @* <div class="ellepsis-bar d-lg-none"> *@
                            @* <i class="icofont-info-square"></i> *@
                            @* </div> *@
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>
@RenderBody()
<footer class="footer-section">
    <div class="footer-middle padding-top padding-bottom" style="background-image: url(../../assets/images/footer/bg.jpg);">
        <div class="container">
            <div class="row justify-content-sm-between padding-lg-top">
                <div class="col-lg-4 col-md-6 col-12">
                    <div class="footer-middle-item-wrapper">
                        <div class="footer-middle-item mb-lg-0">
                            <div class="fm-item-title mb-4">
                                <img src="~/assets/images/logo/logo.png" alt="logo">
                            </div>
                            <div class="fm-item-content">
                                <p class="mb-4">
                                    Upropriate brand economca sound technolog after
                                    covalent technology enable prospective wastng markets whereas
                                    propriate and brand economca sound technolog
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6 col-12">
                    <div class="footer-middle-item-wrapper">
                        <div class="footer-middle-item-3 mb-lg-0">
                            <div class="fm-item-title">
                                <h4>Our Newsletter</h4>
                            </div>
                            <div class="fm-item-content">
                                <p>Bigamer esports organization supported by community leaders</p>
                                <form>
                                    <div class="form-group mb-4">
                                        <input
                                            id="name"
                                            type="text"
                                            name="name"
                                            class="form-control"
                                            placeholder="Your Name"
                                            required>
                                    </div>
                                    <div class="form-group mb-2">
                                        <input
                                            id="email"
                                            type="email"
                                            name="email"
                                            class="form-control"
                                            placeholder="Your Email"
                                            required>
                                    </div>
                                    <button id="subscription-submit" type="button" class="default-button">
                                        <span>Send Massage <i class="icofont-circled-right"></i></span>
                                    </button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="footer-bottom">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="footer-bottom-content text-center">
                        <p>&copy;2021 <a asp-controller="Home" asp-action="Index">BiGamer</a> - eSpost And Gameing HTML Template.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
<script src="~/assets/js/vendor/jquery-3.6.0.min.js"></script>
<script src="~/assets/js/vendor/modernizr-3.11.2.min.js"></script>
<script src="~/assets/js/circularProgressBar.min.js"></script>
<script src="~/assets/js/isotope.pkgd.min.js"></script>
<script src="~/assets/js/swiper.min.js"></script>
<script src="~/assets/js/lightcase.js"></script>
<script src="~/assets/js/waypoints.min.js"></script>
<script src="~/assets/js/wow.min.js"></script>
<script src="~/assets/js/vendor/bootstrap.bundle.min.js"></script>
<script src="~/assets/js/plugins.js"></script>
<script src="~/assets/js/main.js"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>
<script>
document.getElementById('subscription-submit')
    .addEventListener('click', () => {
        let nameInput = document.getElementById('name')
        let emailInput = document.getElementById('email')
       
        if (nameInput.value === '') {
            alert("Write your first name!")    
            return
        }
        
        if (emailInput.value === '') {
            alert("Write your email!")    
            return
        }
        
        fetch('http://localhost:5002/Subscription/Subscribe', {
            method: 'POST',
            headers: {
                  "Content-Type": "application/json"
                },
            body: JSON.stringify({
                email: emailInput.value,
                name: nameInput.value
            })
        })
        .then(response => {
            if (response.status !== 200) {
                response.json()
                .then(json => alert(json.message))
            }
            else {
                alert('Subscription message sent to your email!')
                document.location.reload()
            }
        })
        
    })
</script>